{% set name = "paramtools" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7589b2af0dc7c28a8f6c9fe797b72416fd57b2c619200d1ab7e24280b68c9d14

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - marshmallow >=3.0.0
    - numpy
    - python-dateutil >=2.8.0

test:
  imports:
    - paramtools
    - paramtools.contrib

about:
  home: http://github.com/PSLmodels/ParamTools
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Library for parameter processing and validation with a focus on computational modeling projects '

  description: |
    ParamTools defines the inputs for computational modeling projects,
    facilitates updating the default inputs, and validating the inputs.
    ParamTools is also used to build GUIs.
  doc_url: http://paramtools.readthedocs.io/
  dev_url: https://github.com/PSLmodels/ParamTools

extra:
  recipe-maintainers:
    - hdoupe
