{% set name = "paramtools" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cfb36a54c7deee164b10290a9c3c08fd1b865ee22f6dbecd3cbbc55a2a021b1e

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - marshmallow >=3.0.0
    - numpy
    - python-dateutil >=2.8.0
    - fsspec
    - sortedcontainers

test:
  requires:
    - python {{ python_min }}
  imports:
    - paramtools
    - paramtools.contrib

about:
  home: https://github.com/PSLmodels/ParamTools
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Library for parameter processing and validation with a focus on computational modeling projects '

  description: |
    ParamTools defines the inputs for computational modeling projects,
    facilitates updating the default inputs, and validating the inputs.
    ParamTools is also used to build GUIs.
  doc_url: https://paramtools.dev
  dev_url: https://github.com/PSLmodels/ParamTools

extra:
  recipe-maintainers:
    - hdoupe
    - jdebacker
