{% set name = "paramtools" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4c43928cffc7909b078f04b117c59b1c329340ac9341df52e05c1bcce02223b1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - marshmallow >=3.0.0
    - numpy
    - python-dateutil >=2.8.0

test:
  imports:
    - paramtools
    - paramtools.contrib

about:
  home: http://github.com/PSLmodels/ParamTools
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Library for parameter processing and validation with a focus on computational modeling projects '

  description: |
    ParamTools defines the inputs for computational modeling projects,
    facilitates updating the default inputs, and validating the inputs.
    ParamTools is also used to build GUIs.
  doc_url: https://paramtools.org
  dev_url: https://github.com/PSLmodels/ParamTools

extra:
  recipe-maintainers:
    - hdoupe
