{% set name = "paramtools" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 73eceeaba49f8b1b1bcaf3bdcad949695f911503b09c04456363c0b90fba5d8f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - marshmallow >=3.0.0
    - numpy
    - python-dateutil >=2.8.0
    - fsspec
    - sortedcontainers

test:
  imports:
    - paramtools
    - paramtools.contrib

about:
  home: https://github.com/PSLmodels/ParamTools
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Library for parameter processing and validation with a focus on computational modeling projects '

  description: |
    ParamTools defines the inputs for computational modeling projects,
    facilitates updating the default inputs, and validating the inputs.
    ParamTools is also used to build GUIs.
  doc_url: https://paramtools.dev
  dev_url: https://github.com/PSLmodels/ParamTools

extra:
  recipe-maintainers:
    - hdoupe
