travis:
  secure:
    BINSTAR_TOKEN: QZ6zbyLEmST4WoJbFelcUDcJSB4IyGmULZe7pu2TdhO27tM2Pw452vlSVXlUqvQA2ASpY3KvokSCFi5gDAubrAcCQEla+N+qWjyFsOyR9uf9eibW9y8XCuQOVpiiI5Rrjxa7CJuZJOKyceFWq+LDwLAylRJRVtuGe2Z20p9bNQoWdNf59edOKtgiooXA3lXvSx5Y/X0rE5gmQofW0ajXPhOdPTrDBmJSRRmpTlSx4K0RJvuakuibAQH589YhX1WoAWuttMFJb2G7w+fC6yaFcM179+ckcgKRRZR3Cg2DMQZpW3I4XI88POc4Li6RZLnBa5zPV+lom8AQ6ZGT3fIBjs+6fSLaEKEblaCvE3etHI5RLTRBt9+Tes/qhiBVMAn9UDrEuHUMShxo3DTAnunk+7uq4Iur4OEAS8qRJh+B/aahAUAoGeUpquDz0ZPSq68R5+K3Tg1WanrR+RN3FlcTcVE8+S02QriaqrEPBurVjm4ar9g0aB0ZUfy91vPWuULliUhZ6k3f40NW8Vvi7TlZCVWN8NU7pl4zAk5bsLtg6kb9lhmtvvqpg3SDljIqKk1WKgtLSvg4RNCmRk1VQPUCZ6quu+BkE6TIXX1FpwEwk/q0taLVRQoowycjxA1+bnsqAJaqI1Ur4gaIN4O7TfXHsXjzJimaNfhU7oF/5hkJBuc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
